INFO  | 03/14/2020 04:43:39 PM | File run_exp.py           | Line 26    | Writing log file to exp/GRAN/GRANMixtureBernoulli_FIRSTMM_DB_2020-Mar-14-16-43-39_40913/log_exp_40913.txt
INFO  | 03/14/2020 04:43:39 PM | File run_exp.py           | Line 27    | Exp instance id = 40913
INFO  | 03/14/2020 04:43:39 PM | File run_exp.py           | Line 28    | Exp comment = None
INFO  | 03/14/2020 04:43:39 PM | File run_exp.py           | Line 29    | Config =
INFO  | 03/14/2020 04:43:42 PM | File gran_runner.py       | Line 124   | Train/val/test = 32/8/9
INFO  | 03/14/2020 04:43:42 PM | File gran_runner.py       | Line 137   | No Edges vs. Edges in training set = 955.7817210072006
ERROR | 03/14/2020 04:43:53 PM | File run_exp.py           | Line 42    | Traceback (most recent call last):
  File "run_exp.py", line 38, in main
    runner.train()
  File "/Users/maqiwei/OneDrive/03 Codes/01 Research Codes/original GRAN/runner/gran_runner.py", line 258, in train
    train_loss = float(avg_train_loss.data.cpu().numpy())
AttributeError: 'float' object has no attribute 'data'

